name: Dragan Stepanović
description: Should we be having this problem in the first place?
meta_description: "Dragan Stepanović"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
url: "https://draganstepanovic.com"
baseurl: ""
#permalink: /:title/
google_analytics: 'UA-99087676-3'
plugins: [jekyll-paginate]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      disqus: true

# Details for the RSS feed generator
author: 'Dragan Stepanović'
